from fastapi import APIRouter, HTTPException, Query

from app.models.schemas import (
    GitHubOAuthExchangeRequest,
    GitHubOAuthExchangeResponse,
    GitHubOAuthStartResponse,
    GitHubRepoListRequest,
    GitHubRepoListResponse,
)
from app.services.github_oauth_service import github_oauth_service

router = APIRouter(prefix="/github")


@router.get("/oauth/start")
async def github_oauth_start(
    state: str = Query(..., min_length=1, description="CSRF state generated by frontend"),
    redirect_uri: str = Query(..., min_length=1, description="Frontend callback URI"),
) -> GitHubOAuthStartResponse:
    """Build GitHub OAuth authorization URL for frontend redirects."""
    try:
        authorization_url = github_oauth_service.build_authorization_url(
            state=state,
            redirect_uri=redirect_uri,
        )
        return GitHubOAuthStartResponse(authorization_url=authorization_url)
    except Exception as error:
        raise HTTPException(status_code=400, detail=str(error)) from error


@router.post("/oauth/exchange")
async def github_oauth_exchange(payload: GitHubOAuthExchangeRequest) -> GitHubOAuthExchangeResponse:
    """Exchange GitHub OAuth code for an access token."""
    try:
        data = await github_oauth_service.exchange_code(
            code=payload.code,
            redirect_uri=payload.redirect_uri,
        )
        return GitHubOAuthExchangeResponse(**data)
    except Exception as error:
        raise HTTPException(status_code=400, detail=str(error)) from error


@router.post("/repos")
async def github_repos(payload: GitHubRepoListRequest) -> GitHubRepoListResponse:
    """Return repositories visible to the provided GitHub access token."""
    try:
        repositories = await github_oauth_service.list_repositories(payload.access_token)
        return GitHubRepoListResponse(repositories=repositories)
    except Exception as error:
        raise HTTPException(status_code=400, detail=str(error)) from error
